# Generated by Django 5.0.2 on 2024-04-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_contactquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetails',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverdetails',
            name='ride_request_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
