# Generated by Django 5.0.2 on 2024-04-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_driverdetails_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='phone',
            field=models.CharField(default='9739877225', max_length=15),
        ),
    ]
