# Generated by Django 5.0.2 on 2024-04-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_riderequest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetails',
            name='password',
            field=models.CharField(default='password', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='ride_type',
            field=models.CharField(choices=[('Standard', 'Stamdard'), ('Premium', 'Premium')], max_length=50),
        ),
    ]
