# Generated by Django 5.0.2 on 2024-04-28 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_driverdetails_password_alter_riderequest_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.driverdetails')),
                ('ride_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.riderequest')),
            ],
        ),
    ]
